before:
  hooks:
    - go mod download

builds:
- id: machine-name
  main: ./cmd/machinename
  binary: machine-name
  env:
    - CGO_ENABLED=0
  targets:
    - linux_amd64_v1
    - linux_arm64
    - linux_arm_7
    - darwin_amd64_v1
    - darwin_arm64
    - windows_amd64_v1

archives:
  - id: machine-name
    builds: ["machine-name"]
    name_template: "machine-name{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip

release:
  github:
  prerelease: auto

dockers:
  # machine-name
  - id: machine-name-amd64
    ids:
      - machine-name
    dockerfile: "Dockerfile"
    use: buildx
    image_templates:
    - "ghcr.io/planktoscope/machine-name:latest-amd64"
    - "ghcr.io/planktoscope/machine-name:{{ .Major }}-amd64"
    - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"
  - id: machine-name-arm64v8
    ids:
      - machine-name
    dockerfile: "Dockerfile"
    use: buildx
    goarch: arm64
    image_templates:
    - "ghcr.io/planktoscope/machine-name:latest-arm64v8"
    - "ghcr.io/planktoscope/machine-name:{{ .Major }}-arm64v8"
    - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}-arm64v8"
    - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"
  - id: machine-name-armv7
    ids:
      - machine-name
    dockerfile: "Dockerfile"
    use: buildx
    goarch: arm
    goarm: 7
    image_templates:
    - "ghcr.io/planktoscope/machine-name:latest-armv7"
    - "ghcr.io/planktoscope/machine-name:{{ .Major }}-armv7"
    - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}-armv7"
    - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm/v7"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"

docker_manifests:
  # machine-name
  - name_template: "ghcr.io/planktoscope/machine-name:latest"
    image_templates:
      - "ghcr.io/planktoscope/machine-name:latest-amd64"
      - "ghcr.io/planktoscope/machine-name:latest-arm64v8"
      - "ghcr.io/planktoscope/machine-name:latest-armv7"
  - name_template: "ghcr.io/planktoscope/machine-name:{{ .Major }}"
    image_templates:
      - "ghcr.io/planktoscope/machine-name:{{ .Major }}-amd64"
      - "ghcr.io/planktoscope/machine-name:{{ .Major }}-arm64v8"
      - "ghcr.io/planktoscope/machine-name:{{ .Major }}-armv7"
  - name_template: "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}-arm64v8"
      - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}-armv7"
  - name_template: "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
      - "ghcr.io/planktoscope/machine-name:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
